"""
Database models for QR Code Generator application
Defines User and QRCode models using SQLAlchemy ORM
"""

from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

# Initialize SQLAlchemy
db = SQLAlchemy()


class User(UserMixin, db.Model):
    """
    User model for authentication and QR code ownership
    
    Attributes:
        id (int): Primary key
        username (str): Unique username
        email (str): User email address
        password_hash (str): Hashed password
        created_at (datetime): Account creation timestamp
        qr_codes (relationship): User's generated QR codes
    """
    
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False, index=True)
    email = db.Column(db.String(120), unique=True, nullable=False, index=True)
    password_hash = db.Column(db.String(255), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)

    # Relationship to QR codes
    qr_codes = db.relationship('QRCode', backref='user', lazy='dynamic', cascade='all, delete-orphan')
    
    def set_password(self, password):
        """
        Hash and set the user's password
        
        Args:
            password (str): Plain text password
        """
        self.password_hash = generate_password_hash(password, method='pbkdf2:sha256')
    
    def check_password(self, password):
        """
        Verify password against hash
        
        Args:
            password (str): Plain text password to verify
            
        Returns:
            bool: True if password matches, False otherwise
        """
        return check_password_hash(self.password_hash, password)
    
    def get_qr_count(self):
        """Get total count of QR codes generated by user"""
        return self.qr_codes.count()
    
    def __repr__(self):
        return f'<User {self.username}>'


class QRCode(db.Model):
    """
    QRCode model for storing generated QR code information
    
    Attributes:
        id (int): Primary key
        user_id (int): Foreign key to User
        qr_type (str): Type of QR code (url, text, email, phone, wifi)
        content (str): Content encoded in QR code
        file_name (str): Name of generated QR file
        logo_used (bool): Whether a logo was embedded
        fg_color (str): Foreground color (hex)
        bg_color (str): Background color (hex)
        qr_size (int): Size of QR code
        created_at (datetime): Creation timestamp
    """
    
    __tablename__ = 'qr_codes'
    
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False, index=True)
    qr_type = db.Column(db.String(50), nullable=False)  # url, text, email, phone, wifi
    content = db.Column(db.Text, nullable=False)
    file_name = db.Column(db.String(255), nullable=False)
    logo_used = db.Column(db.Boolean, default=False)
    fg_color = db.Column(db.String(7), default='#000000')  # Foreground color
    bg_color = db.Column(db.String(7), default='#FFFFFF')  # Background color
    qr_size = db.Column(db.Integer, default=10)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False, index=True)
    
    def __repr__(self):
        return f'<QRCode {self.id} - {self.qr_type}>'
    
    def get_file_url(self):
        """Get URL path to the generated QR code file"""
        return f'/static/generated_qr/{self.file_name}'


def init_db(app):
    """
    Initialize database with app context
    
    Args:
        app (Flask): Flask application instance
    """
    with app.app_context():
        db.create_all()
        print("Database initialized successfully!")
